"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { useCustomerAuth } from "@/context/CustomerAuthContext";
import { WantCard, type WantSummary } from "@/components/user/WantCard";
type Revision = { revisionNumber: number; initiator: string; price: unknown; quantity: number; shipping: unknown; delivery: string; condition: string; warranty: string; message: string; expiresAt: string };
type Offer = { id: string; status: string; updatedAt: string; vendor: { id: string; shopName: string; city: string; storeSlug: string | null }; revisions: Revision[] };
function effectiveTotal(r: Revision) { return Number(r.price) * r.quantity + Number(r.shipping); }
function isExpiredOffer(o: Offer) { const latest = o.revisions[0]; return !!latest && ["SUBMITTED", "COUNTERED"].includes(o.status) && new Date(latest.expiresAt).getTime() <= Date.now(); }
function displayStatus(o: Offer) { return isExpiredOffer(o) ? "Expired" : o.status.charAt(0) + o.status.slice(1).toLowerCase(); }
export default function WantPage({ params }: { params: { id: string } }) {
  const { isCustomer, openAuthModal } = useCustomerAuth(); const [want, setWant] = useState<(WantSummary & { description: string; condition: string | null; photo: string | null; needBy: string | null; expiresAt: string; status: string; isOwner: boolean; offers: Offer[] }) | null>(null); const [message, setMessage] = useState("Loading…"); const [joined, setJoined] = useState(false); const [busy, setBusy] = useState(false);
  const load = useCallback(async (signal?: AbortSignal) => {
    try { const r = await fetch(`/api/wants/${params.id}`, { signal }); const d = await r.json(); if (!r.ok) throw new Error(d.error); setWant(d.want); setMessage(""); if (isCustomer) { const s = await fetch(`/api/wants/${params.id}/interest`, { signal }); if (s.ok) setJoined((await s.json()).joined); } } catch(e) { if (!signal?.aborted) setMessage(e instanceof Error ? e.message : "Could not load Want."); }
  }, [params.id, isCustomer]);
  useEffect(() => { const c = new AbortController(); void load(c.signal); return () => c.abort(); }, [load]);
  async function toggle() { if (!isCustomer) { openAuthModal("login"); return; } setBusy(true); try { const r = await fetch(`/api/wants/${params.id}/interest`, { method: joined ? "DELETE" : "PUT" }); const d = await r.json(); if (!r.ok) throw new Error(d.error); setJoined(d.joined); await load(); } catch(e) { setMessage(e instanceof Error ? e.message : "Could not save interest."); } finally { setBusy(false); } }
  return <main className="mx-auto max-w-3xl px-4 py-10"><h1 className="mb-5 text-3xl font-bold">Want details</h1><p role="status">{message}</p>{want && <><WantCard want={want} /><p className="my-5 whitespace-pre-wrap">{want.description}</p><div className="mb-5 flex flex-wrap gap-4 text-sm text-gray-700">{want.condition && <span>Condition: {want.condition}</span>}{want.needBy && <span>Needed by: {new Date(want.needBy).toLocaleDateString("en-PK")}</span>}<span>Expires: {new Date(want.expiresAt).toLocaleDateString("en-PK")}</span></div>{want.photo && <img src={want.photo} alt="" className="mb-5 max-h-80 rounded-2xl object-cover" />}{want.status === "OPEN" && !want.isOwner && <><button disabled={busy} aria-pressed={joined} onClick={() => void toggle()} className="rounded-xl bg-brand-primary px-5 py-3 font-bold">{joined ? "Leave interest" : "Mujhe Bhi Chahiye"}</button><p className="mt-3 text-sm text-gray-600">Interest does not place an order, reserve stock, or charge money.</p></>}{want.status === "PENDING_MODERATION" && <p>Your Want is awaiting moderation.</p>}{want.isOwner && (() => {
  const activeOffers = want.offers.filter(o => ["SUBMITTED", "COUNTERED"].includes(o.status) && !isExpiredOffer(o) && o.revisions[0]);
  const lowestTotal = activeOffers.length > 1 ? Math.min(...activeOffers.map(o => effectiveTotal(o.revisions[0]))) : null;
  return <section className="mt-8"><h2 className="mb-1 text-xl font-bold">Seller offers ({want.offers.length})</h2>{activeOffers.length > 1 && <p className="mb-4 text-sm text-gray-600">Comparing {activeOffers.length} active offers. Prices and delivery below come directly from each seller&apos;s current terms.</p>}{want.offers.length ? <div className="mt-4 grid gap-4 sm:grid-cols-2">{want.offers.map(o => { const latest = o.revisions[0]; const expired = isExpiredOffer(o); const total = latest ? effectiveTotal(latest) : null; const isLowest = lowestTotal !== null && total === lowestTotal && !expired && ["SUBMITTED", "COUNTERED"].includes(o.status); return <article key={o.id} className={`rounded-2xl border bg-white p-5 ${isLowest ? "border-brand-primary ring-1 ring-brand-primary" : ""}`}><div className="flex flex-wrap items-start justify-between gap-3"><Link href={`/stores/${o.vendor.storeSlug || o.vendor.id}`} className="font-bold text-brand-link">{o.vendor.shopName}</Link><span className={`rounded-full px-3 py-1 text-xs font-bold ${expired ? "bg-gray-200 text-gray-700" : "bg-brand-soft"}`}>{displayStatus(o)}</span></div>{isLowest && <span className="mt-2 inline-block rounded-full bg-brand-primary px-2.5 py-0.5 text-xs font-bold text-brand-dark">Lowest price</span>}{latest && <>
    <p className="mt-2 text-lg font-bold">PKR {Number(latest.price).toLocaleString("en-PK")} × {latest.quantity}{latest.quantity > 1 ? ` = PKR ${(Number(latest.price) * latest.quantity).toLocaleString("en-PK")}` : ""}</p>
    <p className="mt-1 text-sm text-gray-600">+ PKR {Number(latest.shipping).toLocaleString("en-PK")} delivery = <strong>PKR {total?.toLocaleString("en-PK")} total</strong></p>
    <p className="mt-2 text-sm text-gray-700">Delivery: {latest.delivery}</p>
    <p className="text-sm text-gray-700">Condition: {latest.condition}{latest.warranty ? ` · Warranty: ${latest.warranty}` : ""}</p>
    <p className="mt-1 text-xs text-gray-500">Expires {new Date(latest.expiresAt).toLocaleString("en-PK")}</p>
    <p className="mt-2 whitespace-pre-wrap text-sm">{latest.message}</p>
  </>}<Link href="/account/offers" className="mt-4 inline-block font-bold text-brand-link">Manage this offer →</Link><details className="mt-3"><summary className="cursor-pointer text-xs font-bold text-gray-500">Revision history ({o.revisions.length})</summary><div className="mt-2 space-y-1">{o.revisions.map(v => <p key={v.revisionNumber} className="text-xs text-gray-600">V{v.revisionNumber} · {v.initiator === "VENDOR" ? "Seller" : "You"} · PKR {Number(v.price).toLocaleString("en-PK")} × {v.quantity} + {Number(v.shipping).toLocaleString("en-PK")} shipping</p>)}</div></details></article>; })}</div> : <p className="rounded-2xl bg-white p-6 text-gray-600">No seller offers yet.</p>}</section>;
})()}</>}</main>;
}
