"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { useCustomerAuth } from "@/context/CustomerAuthContext";
import { WantCard, type WantSummary } from "@/components/user/WantCard";
type Offer = { id: string; status: string; updatedAt: string; vendor: { id: string; shopName: string; city: string; storeSlug: string | null }; revisions: { revisionNumber: number; price: unknown; quantity: number; delivery: string; message: string; expiresAt: string }[] };
export default function WantPage({ params }: { params: { id: string } }) {
  const { isCustomer, openAuthModal } = useCustomerAuth(); const [want, setWant] = useState<(WantSummary & { description: string; status: string; isOwner: boolean; offers: Offer[] }) | null>(null); const [message, setMessage] = useState("Loading…"); const [joined, setJoined] = useState(false); const [busy, setBusy] = useState(false);
  const load = useCallback(async (signal?: AbortSignal) => {
    try { const r = await fetch(`/api/wants/${params.id}`, { signal }); const d = await r.json(); if (!r.ok) throw new Error(d.error); setWant(d.want); setMessage(""); if (isCustomer) { const s = await fetch(`/api/wants/${params.id}/interest`, { signal }); if (s.ok) setJoined((await s.json()).joined); } } catch(e) { if (!signal?.aborted) setMessage(e instanceof Error ? e.message : "Could not load Want."); }
  }, [params.id, isCustomer]);
  useEffect(() => { const c = new AbortController(); void load(c.signal); return () => c.abort(); }, [load]);
  async function toggle() { if (!isCustomer) { openAuthModal("login"); return; } setBusy(true); try { const r = await fetch(`/api/wants/${params.id}/interest`, { method: joined ? "DELETE" : "PUT" }); const d = await r.json(); if (!r.ok) throw new Error(d.error); setJoined(d.joined); await load(); } catch(e) { setMessage(e instanceof Error ? e.message : "Could not save interest."); } finally { setBusy(false); } }
  return <main className="mx-auto max-w-3xl px-4 py-10"><h1 className="mb-5 text-3xl font-bold">Want details</h1><p role="status">{message}</p>{want && <><WantCard want={want} /><p className="my-5 whitespace-pre-wrap">{want.description}</p>{want.status === "OPEN" && !want.isOwner && <><button disabled={busy} aria-pressed={joined} onClick={() => void toggle()} className="rounded-xl bg-brand-primary px-5 py-3 font-bold">{joined ? "Leave interest" : "Mujhe Bhi Chahiye"}</button><p className="mt-3 text-sm text-gray-600">Interest does not place an order, reserve stock, or charge money.</p></>}{want.status === "PENDING_MODERATION" && <p>Your Want is awaiting moderation.</p>}{want.isOwner && <section className="mt-8"><h2 className="mb-4 text-xl font-bold">Seller offers ({want.offers.length})</h2>{want.offers.length ? <div className="space-y-4">{want.offers.map(o => { const latest = o.revisions[0]; return <article key={o.id} className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><Link href={`/stores/${o.vendor.storeSlug || o.vendor.id}`} className="font-bold text-brand-link">{o.vendor.shopName}</Link><span className="rounded-full bg-brand-soft px-3 py-1 text-xs font-bold capitalize">{o.status}</span></div>{latest && <><p className="mt-2 text-lg font-bold">PKR {Number(latest.price).toLocaleString("en-PK")} × {latest.quantity}</p><p className="mt-1 text-sm text-gray-600">Delivery: {latest.delivery}</p><p className="mt-2 whitespace-pre-wrap text-sm">{latest.message}</p></>}<Link href="/account?tab=offers" className="mt-4 inline-block font-bold text-brand-link">Manage this offer →</Link></article>; })}</div> : <p className="rounded-2xl bg-white p-6 text-gray-600">No seller offers yet.</p>}</section>}</>}</main>;
}
