"use client";
import {useEffect,useRef,useState} from "react";
import Link from "next/link";
import {ChevronDown,Menu} from "lucide-react";
import {useQuery} from "@tanstack/react-query";
export function useNavCategories(){
 return useQuery<{id:number;name:string}[]>({queryKey:["nav-categories"],queryFn:async()=>{const r=await fetch("/api/categories");if(!r.ok)throw Error("Categories unavailable");return r.json();},staleTime:60000});
}
export function CategoryNavigation(){
 const {data:categories=[],isLoading,isError}=useNavCategories();const [open,setOpen]=useState(false);const root=useRef<HTMLDivElement>(null);const button=useRef<HTMLButtonElement>(null);const menu=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!open)return;const outside=(e:Event)=>{if(!root.current?.contains(e.target as Node))setOpen(false);};const key=(e:KeyboardEvent)=>{if(e.key==="Escape"){setOpen(false);button.current?.focus();}};document.addEventListener("pointerdown",outside);document.addEventListener("focusin",outside);document.addEventListener("keydown",key);return()=>{document.removeEventListener("pointerdown",outside);document.removeEventListener("focusin",outside);document.removeEventListener("keydown",key);};},[open]);
 return <div className="border-b border-black/10 bg-[#fafbf7]"><div ref={root} className="relative mx-auto flex h-12 max-w-7xl items-center px-4 sm:px-6"><button ref={button} type="button" aria-expanded={open} aria-controls="category-dropdown" onClick={()=>setOpen(!open)} onKeyDown={e=>{if(e.key==="ArrowDown"){e.preventDefault();setOpen(true);requestAnimationFrame(()=>menu.current?.querySelector("a")?.focus());}}} className="flex h-10 shrink-0 items-center gap-2 rounded-lg px-2 text-xs font-bold text-emerald-900 hover:bg-lime-100 focus-visible:outline-emerald-700"><Menu className="h-4 w-4"/>Categories<ChevronDown className="h-3 w-3"/></button><nav aria-label="Category strip" className="hide-scrollbar ml-2 flex min-w-0 flex-1 items-center gap-1 overflow-x-auto border-l pl-2">{categories.map(c=><Link key={c.id} href={`/products?category=${encodeURIComponent(c.name)}`} className="shrink-0 rounded-lg px-3 py-2 text-xs font-semibold text-emerald-900 hover:bg-lime-100">{c.name}</Link>)}</nav>{open&&<div ref={menu} id="category-dropdown" className="absolute left-4 right-4 top-full z-[70] max-h-[65dvh] overflow-y-auto rounded-b-2xl border bg-white p-4 shadow-xl sm:right-auto sm:w-[520px]"><nav aria-label="All categories" className="grid grid-cols-2 gap-1"><Link className="col-span-2 rounded-lg px-3 py-3 font-bold text-emerald-900 hover:bg-lime-100" href="/products" onClick={()=>setOpen(false)}>All products</Link>{categories.map(c=><Link key={c.id} onClick={()=>setOpen(false)} href={`/products?category=${encodeURIComponent(c.name)}`} className="rounded-lg px-3 py-3 text-sm text-emerald-900 hover:bg-lime-100 focus:bg-lime-100">{c.name}</Link>)}</nav>{isLoading&&<p role="status" className="p-3 text-sm">Loading categories…</p>}{isError&&<p role="status" className="p-3 text-sm">Categories are temporarily unavailable. Browse all products.</p>}{!isLoading&&!isError&&!categories.length&&<p className="p-3 text-sm">Browse all products while categories are being added.</p>}</div>}</div></div>;
}
