"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { useCustomerAuth } from "@/context/CustomerAuthContext";
import { useCart } from "@/context/CartContext";
type Revision = { id: string; productId: string | null; price: string; quantity: number; shipping: string; delivery: string; condition: string; warranty: string; message: string; expiresAt: string; revisionNumber: number; initiator: string };
type Offer = { id: string; status: string; want: { title: string; city: string }; vendor?: { shopName: string }; revisions: Revision[] };
export function OfferCenter({ vendor = false }: { vendor?: boolean }) {
  return vendor ? <OfferCenterBody vendor isCustomer openAuthModal={() => {}} addItem={() => {}} /> : <CustomerOfferCenter />;
}
function CustomerOfferCenter() {
  const { isCustomer, openAuthModal } = useCustomerAuth(); const { addItem } = useCart();
  return <OfferCenterBody isCustomer={isCustomer} openAuthModal={openAuthModal} addItem={addItem} />;
}
function OfferCenterBody({ vendor = false, isCustomer, openAuthModal, addItem }: { vendor?: boolean; isCustomer: boolean; openAuthModal: (tab: "login") => void; addItem: ReturnType<typeof useCart>["addItem"] }) {
  const [offers, setOffers] = useState<Offer[]>([]); const [message, setMessage] = useState("Loading…"); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { const r = await fetch(vendor ? "/api/vendor/offers" : "/api/account/offers"); const d = await r.json(); if (!r.ok) throw new Error(d.error); setOffers(d.offers); setMessage(d.offers.length ? "" : "No offers yet."); } catch(e) { setMessage(e instanceof Error ? e.message : "Could not load offers."); } }, [vendor]);
  useEffect(() => { if (vendor || isCustomer) void load(); }, [vendor, isCustomer, load]);
  async function action(offer: Offer, action: string, fields?: FormData) { setBusy(true); try {
    const latest = offer.revisions[0]; const terms = fields ? { productId: latest.productId, price: Number(fields.get("price")), quantity: Number(fields.get("quantity")), shipping: Number(fields.get("shipping")), delivery: String(fields.get("delivery")), condition: latest.condition, warranty: String(fields.get("warranty")), message: String(fields.get("message")), expiresAt: new Date(String(fields.get("expiry"))).toISOString() } : {};
    const r = await fetch(`/api/offers/${offer.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, revisionId: latest.id, idempotencyKey: crypto.randomUUID(), ...terms }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error);
    if (d.quote) { const q = await fetch(`/api/account/quotes/${d.quote.id}`); const data = await q.json(); if (!q.ok) throw new Error(data.error); const rev = data.quote.revision;
      addItem({ productId: rev.productId, name: rev.product.name, price: Number(rev.price), quantity: rev.quantity, maxStock: rev.product.stock, image: "", quoteId: d.quote.id, quoteShipping: Number(rev.shipping) });
      setMessage("Accepted quote added to your cart. Checkout this quoted item on its own; remove other cart items first. Acceptance is not payment.");
    } else { await load(); }
  } catch(e) { setMessage(e instanceof Error ? e.message : "Could not update offer."); } finally { setBusy(false); } }
  if (!vendor && !isCustomer) return <button onClick={() => openAuthModal("login")} className="rounded-xl bg-brand-primary p-3">Sign in to view offers</button>;
  return <><p className="my-4" role="status">{message}</p>{!vendor && <Link href="/cart" className="text-brand-link underline">View personal cart</Link>}<div className="mt-5 space-y-5">{offers.map(o => { const r = o.revisions[0]; if (!r) return null; return <article key={o.id} className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-bold">{o.want.title}</h2><p className="my-2">{o.vendor?.shopName} · {o.status} · {o.want.city}</p><p className="font-bold">PKR {(Number(r.price) * r.quantity + Number(r.shipping)).toLocaleString("en-PK")} full payable</p><p className="my-2 text-sm">{r.quantity} × PKR {r.price} + PKR {r.shipping} delivery</p><p>{r.condition} · {r.delivery}</p><p>Warranty: {r.warranty || "Not specified"}</p><p>Expires: {new Date(r.expiresAt).toLocaleString()}</p><p className="my-3 whitespace-pre-wrap">{r.message}</p>{["SUBMITTED","COUNTERED"].includes(o.status) && <><div className="my-4 flex flex-wrap gap-3">{!vendor && r.initiator === "VENDOR" && <button disabled={busy} onClick={() => void action(o,"accept")} className="rounded-xl bg-brand-primary p-3">Accept & add to cart</button>}<button disabled={busy} onClick={() => void action(o,vendor ? "withdraw" : "reject")} className="rounded-xl border p-3">{vendor ? "Withdraw" : "Reject"}</button></div><details><summary className="cursor-pointer font-bold">{vendor ? "Revise offer" : "Counter offer"}</summary><form className="joro-form mt-4 grid gap-3 sm:grid-cols-2" onSubmit={e => { e.preventDefault(); void action(o, vendor ? "revise" : "counter", new FormData(e.currentTarget)); }}><label>Unit price PKR<input type="number" name="price" defaultValue={r.price} min={1} step="0.01" required /></label><label>Quantity<input name="quantity" type="number" defaultValue={r.quantity} min={1} required /></label><label>Shipping PKR<input name="shipping" type="number" defaultValue={r.shipping} min={0} step="0.01" required /></label><label>Estimated delivery<input name="delivery" defaultValue={r.delivery} required /></label><label>Warranty<input name="warranty" defaultValue={r.warranty} /></label><label>Expiry<input name="expiry" type="datetime-local" required /></label><label>Message<textarea name="message" maxLength={5000} /></label><button disabled={busy} className="rounded-xl bg-brand-primary p-3">Send terms</button></form></details></>}<details className="mt-4"><summary>Revision history</summary>{o.revisions.map(v => <p className="mt-2 text-sm" key={v.id}>V{v.revisionNumber} · {v.initiator} · PKR {v.price} × {v.quantity} + {v.shipping} shipping · {v.delivery} · {v.warranty} · {v.message}</p>)}</details></article>; })}</div></>;
}