"use client";
import { useEffect, useState } from "react";
import { useCart, type CartLine } from "@/context/CartContext";
import { useCustomerAuth } from "@/context/CustomerAuthContext";
type Service = { id: string; name: string; description: string; price: string; cities: string[]; durationMinutes: number; leadDays: number; warranty: string; cancellationTerms: string };
export function ProductServices({ line }: { line: CartLine }) {
  const { addItem } = useCart(); const { requireCustomer } = useCustomerAuth(); const [services, setServices] = useState<Service[]>([]); const [city, setCity] = useState(""); const [message, setMessage] = useState("");
  useEffect(() => { const c = new AbortController(); fetch(`/api/products/${line.productId}/services`, { signal: c.signal }).then(async r => { if (!r.ok) return; setServices((await r.json()).services); }).catch(() => { if (!c.signal.aborted) setMessage("Service availability could not be loaded."); }); return () => c.abort(); }, [line.productId]);
  if (!services.length) return null;
  return <section className="joro-form mt-6 rounded-2xl border bg-white p-5"><h2 className="text-xl font-bold">Complete Your Purchase</h2><label className="my-3">Your delivery city<input value={city} onChange={e => setCity(e.target.value)} /></label>{services.map(s => { const eligible = s.cities.some(c => c.toLowerCase() === city.trim().toLowerCase()); return <article key={s.id} className="mt-4 border-t pt-4"><h3 className="font-bold">{s.name} · PKR {Number(s.price).toLocaleString("en-PK")} per unit</h3><p className="my-2 text-sm">{s.cities.join(" / ")} · Lead time {s.leadDays} days · {s.durationMinutes} minutes</p><details><summary>Includes, warranty & cancellation</summary><p className="my-2 whitespace-pre-wrap">{s.description}</p><p>Warranty: {s.warranty || "Not specified"}</p><p>{s.cancellationTerms}</p></details>{city && !eligible && <p className="mt-2 text-sm text-amber-800">Service currently unavailable in your city.</p>}<button disabled={!eligible || line.quantity < 1 || line.maxStock < line.quantity} onClick={() => requireCustomer(() => { addItem({ ...line, serviceId: s.id, serviceName: s.name, servicePrice: Number(s.price) }); setMessage("Product and service added to your cart."); }, "login")} className="mt-3 rounded-xl bg-brand-primary p-3 font-bold disabled:opacity-50">Add product with service</button></article>; })}<p role="status" className="mt-3 text-sm">{message}</p></section>;
}