"use client";
import { useCallback, useEffect, useState } from "react";
import { NeedHelpButton } from "@/components/support/NeedHelpButton";
type Job = { id: string; status: string; scheduledAt: string | null; refundStatus: string; snapshot: { name: string; warranty: string; total: string; city: string; cancellationTerms: string }; order: { orderNumber: string }; events: { id: string; status: string; note: string }[] };
export function ServiceBookings({ role = "customer" }: { role?: "customer" | "vendor" | "admin" }) {
  const [jobs, setJobs] = useState<Job[]>([]); const [message, setMessage] = useState("Loading…"); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { const r = await fetch(`/api/services/bookings?role=${role}`); const d = await r.json(); if (!r.ok) throw new Error(d.error); setJobs(d.bookings); setMessage(d.bookings.length ? "" : "No service bookings yet."); } catch(e) { setMessage(e instanceof Error ? e.message : "Could not load bookings."); } }, [role]);
  useEffect(() => { void load(); }, [load]);
  async function change(e: React.FormEvent<HTMLFormElement>, id: string) { e.preventDefault(); const f = new FormData(e.currentTarget); setBusy(true); try { const r = await fetch("/api/services/bookings", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, role, status: f.get("status"), note: f.get("note"), ...(f.get("date") ? { scheduledAt: new Date(String(f.get("date"))).toISOString() } : {}) }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error); await load(); } catch(e) { setMessage(e instanceof Error ? e.message : "Could not update service."); } finally { setBusy(false); } }
  return <><p className="my-4" role="status">{message}</p>{jobs.map(j => <article className="mb-4 rounded-2xl border bg-white p-5" key={j.id}><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-bold">{j.snapshot.name}</h2>{role !== "admin" && <NeedHelpButton role={role} resourceType="SERVICE_BOOKING" resourceId={j.id} />}</div><p className="my-2">Order {j.order.orderNumber} · {j.status} · PKR {j.snapshot.total}</p><p>{j.snapshot.city} · {j.scheduledAt ? new Date(j.scheduledAt).toLocaleString() : "Scheduling required"}</p><p className="my-2">Warranty: {j.snapshot.warranty || "Not specified"}</p><details><summary>Cancellation terms & history</summary><p>{j.snapshot.cancellationTerms}</p>{j.events.map(ev => <p key={ev.id} className="my-2 text-sm">{ev.status} · {ev.note}</p>)}</details>{j.refundStatus !== "NONE" && <p className="mt-3 text-amber-800">Refund requires admin review. No refund has been confirmed here.</p>}{!["COMPLETED","CANCELLED","FAILED"].includes(j.status) && <form onSubmit={e => void change(e,j.id)} className="joro-form mt-4 grid gap-3 sm:grid-cols-2"><label>Action<select name="status">{(role === "customer" ? ["SCHEDULE_REQUIRED"] : role === "vendor" ? ["CONFIRMED","SCHEDULE_REQUIRED","SCHEDULED","IN_PROGRESS"] : ["CONFIRMED","SCHEDULE_REQUIRED","SCHEDULED","IN_PROGRESS","COMPLETED","CANCELLED","FAILED"]).map(s => <option key={s}>{s}</option>)}</select></label><label>Requested / scheduled date<input type="datetime-local" name="date" /></label><label>Note / evidence<input name="note" minLength={3} maxLength={2000} required /></label><button disabled={busy} className="self-end rounded-xl bg-brand-primary p-3">Save</button></form>}</article>)}</>;
}