"use client";
import { useCallback, useEffect, useState } from "react";
type Campaign = { id: string; vendorId: string; title: string; subtitle: string; desktopImage: string; mobileImage: string; ctaText: string; priority: number; startAt: string; endAt: string; status: string; isSponsored: boolean; vendor: { shopName: string } };
export default function Promotions() {
  const [campaigns, setCampaigns] = useState<Campaign[]>([]); const [vendors, setVendors] = useState<{ id: string; shopName: string }[]>([]); const [editing, setEditing] = useState<Campaign | null>(null); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { const r = await fetch("/api/admin/vendor-promotions"); const d = await r.json(); if (!r.ok) throw new Error(d.error); setCampaigns(d.campaigns); setVendors(d.vendors); } catch(e) { setMessage(e instanceof Error ? e.message : "Could not load promotions."); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function save(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); setBusy(true); try { const r = await fetch("/api/admin/vendor-promotions", { method: editing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...(editing ? { id: editing.id } : {}), vendorId: f.get("vendorId"), title: f.get("title"), subtitle: f.get("subtitle"), desktopImage: f.get("desktopImage"), mobileImage: f.get("mobileImage"), ctaText: f.get("ctaText"), priority: Number(f.get("priority")), startAt: new Date(String(f.get("startAt"))).toISOString(), endAt: new Date(String(f.get("endAt"))).toISOString(), status: f.get("status"), isSponsored: f.get("isSponsored") === "on", reason: f.get("reason") }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error); setEditing(null); setMessage("Campaign saved."); await load(); } catch(e) { setMessage(e instanceof Error ? e.message : "Could not save campaign."); } finally { setBusy(false); } }
  return <main className="mx-auto max-w-5xl p-6"><h1 className="text-3xl font-bold">Vendor promotions</h1><p className="my-4" role="status">{message}</p><form key={editing?.id || "new"} onSubmit={e => void save(e)} className="joro-form grid gap-4 rounded-2xl bg-white p-6 sm:grid-cols-2"><label>Approved vendor<select name="vendorId" defaultValue={editing?.vendorId} required><option value="">Select vendor</option>{vendors.map(v => <option value={v.id} key={v.id}>{v.shopName}</option>)}</select></label><label>Headline<input name="title" defaultValue={editing?.title} maxLength={160} required /></label><label>Subtitle<input name="subtitle" defaultValue={editing?.subtitle || ""} maxLength={300} /></label><label>CTA text<input name="ctaText" defaultValue={editing?.ctaText || "View Store"} required /></label><label>Desktop image URL<input name="desktopImage" defaultValue={editing?.desktopImage || ""} placeholder="Uploaded image URL" /></label><label>Mobile image URL<input name="mobileImage" defaultValue={editing?.mobileImage || ""} placeholder="Uploaded image URL" /></label><label>Starts (local time)<input type="datetime-local" name="startAt" required /></label><label>Ends (local time)<input type="datetime-local" name="endAt" required /></label><label>Priority<input name="priority" type="number" defaultValue={editing?.priority || 0} min={0} max={1000} required /></label><label>Status<select name="status" defaultValue={editing?.status || "DRAFT"}><option>DRAFT</option><option>ACTIVE</option><option>DISABLED</option><option>ARCHIVED</option></select></label><label><input type="checkbox" name="isSponsored" defaultChecked={editing?.isSponsored} /> Sponsored placement</label><label>Audit reason<input name="reason" minLength={3} required /></label><button disabled={busy} className="rounded-xl bg-brand-primary px-5 py-3 font-bold">{busy ? "Saving…" : editing ? "Update campaign" : "Create campaign"}</button>{editing && <button type="button" onClick={() => setEditing(null)}>Cancel edit</button>}</form><div className="mt-6 space-y-3">{campaigns.map(c => <article key={c.id} className="rounded-2xl border bg-white p-5"><h2 className="font-bold">{c.title}</h2><p>{c.vendor.shopName} · {c.status} · {c.isSponsored ? "Sponsored" : "Featured"}</p><p className="my-2 text-sm">{new Date(c.startAt).toLocaleString()} — {new Date(c.endAt).toLocaleString()}</p><button onClick={() => setEditing(c)} className="text-brand-link underline">Edit campaign</button></article>)}</div></main>;
}