"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useCustomerAuth } from "@/context/CustomerAuthContext";
export default function TogetherPage() {
  const { isCustomer, openAuthModal } = useCustomerAuth(); const router = useRouter(); const [rooms, setRooms] = useState<{ id: string; name: string; archived: boolean }[]>([]); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { if (!isCustomer) return; const c = new AbortController(); fetch("/api/together", { signal: c.signal }).then(async r => { const d = await r.json(); if (!r.ok) throw new Error(d.error); setRooms(d.rooms); }).catch(e => { if (!c.signal.aborted) setMessage(e.message); }); return () => c.abort(); }, [isCustomer]);
  async function create(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); if (!isCustomer) { openAuthModal("login"); return; } const f = new FormData(e.currentTarget); setBusy(true); try { const r = await fetch("/api/together", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: f.get("name") }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error); router.push(`/together/${d.room.id}`); } catch(e) { setMessage(e instanceof Error ? e.message : "Could not create room."); } finally { setBusy(false); } }
  return <main className="mx-auto max-w-5xl px-4 py-10"><h1 className="text-3xl font-bold">Shop Together</h1><p className="my-4">Plan family, wedding, or new-home shopping together. Every buyer uses their own cart, address, and payment.</p><form onSubmit={e => void create(e)} className="joro-form mb-6 flex flex-wrap items-end gap-3"><label>Shopping room name<input name="name" maxLength={160} required placeholder="Family shopping" /></label><button disabled={busy} className="rounded-xl bg-brand-primary p-3 font-bold">Create room</button></form><p role="status">{message}</p>{!isCustomer && <button onClick={() => openAuthModal("login")} className="my-4 underline">Sign in to view your rooms</button>}<div className="grid gap-4 sm:grid-cols-2">{rooms.map(r => <Link key={r.id} href={`/together/${r.id}`} className="rounded-2xl border bg-white p-5 font-bold">{r.name}{r.archived ? " · Archived" : ""}</Link>)}</div></main>;
}