"use client";
import { useCallback, useEffect, useState } from "react";
type Want = { id: string; title: string; description: string | null; city: string; status: string };
export default function AdminWants() {
  const [wants, setWants] = useState<Want[]>([]); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { const r = await fetch("/api/admin/wants"); const d = await r.json(); if (!r.ok) throw new Error(d.error); setWants(d.wants); } catch(e) { setError(e instanceof Error ? e.message : "Could not load Wants."); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function moderate(event: React.FormEvent<HTMLFormElement>, id: string) { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); setError(""); try { const r = await fetch("/api/admin/wants", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, status: form.get("status"), reason: form.get("reason") }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error); await load(); } catch(e) { setError(e instanceof Error ? e.message : "Could not moderate Want."); } finally { setBusy(false); } }
  return <main className="p-6"><h1 className="text-3xl font-bold">Want moderation</h1><p role="alert" className="my-4 text-red-700">{error}</p><p className="mb-4 text-sm">Reject requests containing private contact details or inappropriate content.</p>{wants.map(w => <article key={w.id} className="mb-4 rounded-2xl border bg-white p-5"><h2 className="text-xl font-bold">{w.title}</h2><p className="my-2">{w.city} · {w.status}</p><p className="whitespace-pre-wrap">{w.description}</p><form onSubmit={e => void moderate(e, w.id)} className="joro-form mt-4 grid gap-3 sm:grid-cols-3"><label>Decision<select name="status"><option value="OPEN">Approve</option><option value="REJECTED">Reject</option><option value="CLOSED">Close</option></select></label><label>Reason<input name="reason" required minLength={3} maxLength={2000} /></label><button disabled={busy} className="self-end rounded-xl bg-brand-primary p-3">Save decision</button></form></article>)}{!wants.length && !error && <p>No Wants to moderate.</p>}</main>;
}