"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import toast from "react-hot-toast";
import { Bell, CheckCheck } from "lucide-react";
import { useCustomerAuth } from "@/context/CustomerAuthContext";

type Row = { id: string; type: string; title: string; message: string; link: string | null; isRead: boolean; createdAt: string };

export default function CustomerNotificationsPage() {
  const { openAuthModal } = useCustomerAuth(); const [rows, setRows] = useState<Row[]>([]); const [unread, setUnread] = useState(0); const [loading, setLoading] = useState(true); const [unauthorized, setUnauthorized] = useState(false);
  const load = useCallback(async () => { setLoading(true); try { const response = await fetch("/api/customer/notifications"); if (response.status === 401) { setUnauthorized(true); return; } const data = await response.json(); if (!response.ok) throw new Error(data.error || "Could not load notifications"); setRows(data.notifications ?? []); setUnread(data.unread ?? 0); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not load notifications"); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function read(row: Row) { if (!row.isRead) { await fetch(`/api/customer/notifications/${row.id}`, { method: "PATCH" }); setRows((current) => current.map((item) => item.id === row.id ? { ...item, isRead: true } : item)); setUnread((value) => Math.max(0, value - 1)); } }
  async function readAll() { const response = await fetch("/api/customer/notifications", { method: "PATCH" }); if (!response.ok) return toast.error("Could not mark notifications read"); setRows((current) => current.map((row) => ({ ...row, isRead: true }))); setUnread(0); }
  if (loading) return <main className="mx-auto max-w-4xl px-4 py-20 text-center text-darkText/50">Loading notifications…</main>;
  if (unauthorized) return <main className="mx-auto max-w-lg px-4 py-20 text-center"><section className="rounded-2xl border border-borderGray bg-white p-8 shadow-card"><Bell className="mx-auto h-8 w-8 text-brand-link" /><h1 className="mt-3 text-2xl font-black text-brand-dark">Sign in for notifications</h1><p className="mt-2 text-sm text-darkText/60">Order, offer, return and refund updates are private.</p><button onClick={() => openAuthModal("login")} className="mt-6 w-full rounded-xl bg-brand-primary px-4 py-3 font-black text-brand-dark">Sign in</button></section></main>;
  return <main className="mx-auto max-w-4xl px-4 py-9 sm:px-6"><div className="flex items-end justify-between gap-3"><div><p className="text-sm font-black uppercase tracking-wider text-brand-link">Account updates</p><h1 className="text-3xl font-black text-brand-dark">Notifications</h1><p className="mt-1 text-sm text-darkText/55">{unread} unread</p></div>{unread ? <button onClick={() => void readAll()} className="inline-flex items-center gap-2 rounded-xl bg-brand-soft px-4 py-2.5 text-sm font-black text-brand-link"><CheckCheck className="h-4 w-4" />Mark all read</button> : null}</div><section className="mt-6 space-y-3">{rows.length ? rows.map((row) => { const content = <article className={`rounded-2xl border p-5 shadow-card transition ${row.isRead ? "border-borderGray bg-white" : "border-brand-primary bg-brand-soft/30"}`}><div className="flex items-start gap-3"><span className="mt-1 h-2.5 w-2.5 shrink-0 rounded-full bg-brand-primary" /><div><h2 className="font-black text-brand-dark">{row.title}</h2><p className="mt-1 text-sm leading-6 text-darkText/65">{row.message}</p><p className="mt-2 text-xs text-darkText/40">{new Date(row.createdAt).toLocaleString("en-PK")}</p></div></div></article>; return row.link ? <Link key={row.id} href={row.link} onClick={() => void read(row)}>{content}</Link> : <button key={row.id} onClick={() => void read(row)} className="block w-full text-left">{content}</button>; }) : <div className="rounded-2xl border border-dashed border-borderGray bg-white p-10 text-center"><Bell className="mx-auto h-7 w-7 text-darkText/25" /><p className="mt-3 font-black text-brand-dark">No notifications yet</p><p className="mt-1 text-sm text-darkText/50">Important account updates will appear here.</p></div>}</section></main>;
}
