"use client";
import { useCallback, useEffect, useState } from "react";
import { useSession } from "next-auth/react";
import Link from "next/link";
import { useCustomerAuth } from "@/context/CustomerAuthContext";
import { safeAccountLink } from "@/lib/customer-account-policy";
type Row = { id: string; title: string; message: string; link: string | null; isRead: boolean; createdAt: string };
export default function NotificationsPage() {
  const { data: session, status } = useSession(); const { openAuthModal } = useCustomerAuth(); const customerId = session?.user?.role === "customer" ? session.user.id : "";
  const [rows,setRows] = useState<Row[]>([]); const [ownerId,setOwnerId] = useState(""); const [unread,setUnread] = useState(0); const [message,setMessage] = useState(""); const [loading,setLoading] = useState(true); const [busy,setBusy] = useState(false);
  const load = useCallback(async (signal?: AbortSignal) => { if (!customerId) return; setLoading(true); try { const r = await fetch("/api/customer/notifications",{ signal }); const d = await r.json(); if (!r.ok) throw new Error(d.error); if (!signal?.aborted) { setRows(d.notifications); setUnread(d.unread); setOwnerId(customerId); setMessage(""); } } catch(e) { if (!signal?.aborted) setMessage(e instanceof Error ? e.message : "Could not load notifications."); } finally { if (!signal?.aborted) setLoading(false); } },[customerId]);
  useEffect(() => { setRows([]); const c = new AbortController(); void load(c.signal); return () => c.abort(); },[load]);
  async function mark(id?: string) { setBusy(true); try { const r = await fetch(`/api/customer/notifications${id ? `/${id}` : ""}`,{method:"PATCH"}); const d = await r.json(); if (!r.ok) throw new Error(d.error); await load(); } catch(e) { setMessage(e instanceof Error ? e.message : "Could not mark notification read."); } finally { setBusy(false); } }
  if (status === "loading") return <p className="p-8">Loading…</p>;
  if (!customerId) return <main className="p-8"><h1 className="text-3xl font-bold">Notifications</h1><button onClick={() => openAuthModal("login")} className="mt-4 rounded-xl bg-brand-primary p-3">Sign in</button></main>;
  const current = ownerId === customerId ? rows : []; const currentUnread = ownerId === customerId ? unread : 0;
  return <main className="mx-auto max-w-4xl px-4 py-8"><h1 className="text-3xl font-bold">Notifications</h1><p className="my-3" role="status">{message || (loading ? "Loading notifications…" : `${currentUnread} unread`)}</p>{currentUnread > 0 && <button disabled={busy} onClick={() => void mark()} className="mb-5 rounded-xl bg-brand-soft p-3 font-bold">Mark all read</button>}<div className="space-y-4">{current.map(row => { const href = safeAccountLink(row.link); return <article key={row.id} className={`rounded-2xl border p-5 ${row.isRead ? "bg-white" : "border-brand-primary bg-brand-soft/30"}`}><h2 className="text-lg font-bold">{row.title}{!row.isRead ? " · Unread" : ""}</h2><p className="my-2">{row.message}</p><p className="text-sm text-darkText/65">{new Date(row.createdAt).toLocaleString("en-PK")}</p><div className="mt-4 flex gap-4 text-sm font-bold text-brand-link">{href && <Link href={href}>View update</Link>}{!row.isRead && <button disabled={busy} onClick={() => void mark(row.id)}>Mark read</button>}</div></article>; })}</div>{!loading && !message && !current.length && <p className="mt-5 rounded-2xl border border-dashed bg-white p-8 text-center">No notifications yet. Real account updates will appear here.</p>}{message && <button onClick={() => void load()} className="mt-4 underline">Try again</button>}</main>;
}