"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { useSession } from "next-auth/react";
import { useCustomerAuth } from "@/context/CustomerAuthContext";
import { formatPKR } from "@/lib/format";
type Order = { id: string; orderNumber: string; orderStatus: string; paymentStatus: string; paymentMethod: string; totalAmount: number; customerName: string; customerAddress: string; city: string; customerPhone: string; trackingNumber: string | null; createdAt: string; canCancel: boolean; hasDeliveredItems: boolean; orderItems: { id: string; name: string; price: number; quantity: number; variant: string | null }[]; vendorShopOrders: { shopOrderNumber: string; status: string; trackingNumber: string | null }[] };
export default function AccountOrder({ params }: { params: { id: string } }) {
  const { data: session, status } = useSession(); const { openAuthModal } = useCustomerAuth(); const customerId = session?.user?.role === "customer" ? session.user.id : "";
  const [order,setOrder] = useState<Order | null>(null); const [ownerId,setOwnerId] = useState(""); const [message,setMessage] = useState("Loading order…"); const [busy,setBusy] = useState(false);
  const load = useCallback(async (signal?: AbortSignal) => { if (!customerId) return; try { const r = await fetch(`/api/customer/orders/${encodeURIComponent(params.id)}`, { signal }); const d = await r.json(); if (!r.ok) throw new Error(d.error); if (!signal?.aborted) { setOrder(d.order); setOwnerId(customerId); setMessage(""); } } catch(e) { if (!signal?.aborted) setMessage(e instanceof Error ? e.message : "Could not load order."); } }, [customerId,params.id]);
  useEffect(() => { setOrder(null); const c = new AbortController(); void load(c.signal); return () => c.abort(); }, [load]);
  async function cancel(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); setBusy(true); const f = new FormData(e.currentTarget); try { const r = await fetch(`/api/orders/${params.id}/cancel`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ reason: f.get("reason") }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error); await load(); setMessage("Order cancelled."); } catch(e) { setMessage(e instanceof Error ? e.message : "Could not cancel order."); } finally { setBusy(false); } }
  if (status === "loading") return <p className="p-8">Loading…</p>;
  if (!customerId) return <main className="p-8"><h1 className="text-2xl font-bold">Your order</h1><button onClick={() => openAuthModal("login")} className="mt-4 rounded-xl bg-brand-primary p-3">Sign in</button></main>;
  const current = ownerId === customerId ? order : null;
  return <main className="mx-auto max-w-4xl px-4 py-8"><Link href="/account?tab=orders" className="text-brand-link underline">Order history</Link><p role="status" className="my-4">{message}</p>{current && <><h1 className="text-3xl font-bold">Order {current.orderNumber}</h1><p className="my-3">{current.orderStatus} · Payment {current.paymentStatus} · {current.paymentMethod.replaceAll("_"," ")}</p><section className="my-5 rounded-2xl border bg-white p-5"><h2 className="text-xl font-bold">Items</h2><ul className="mt-4 space-y-3">{current.orderItems.map(i => <li key={i.id} className="flex flex-wrap justify-between gap-3"><span>{i.name}{i.variant ? ` · ${i.variant}` : ""} × {i.quantity}</span><span>{formatPKR(i.price * i.quantity)}</span></li>)}</ul><p className="mt-5 border-t pt-4 font-bold">Order total: {formatPKR(current.totalAmount)}</p></section><section className="my-5 rounded-2xl border bg-white p-5"><h2 className="text-xl font-bold">Delivery</h2><p className="mt-3">{current.customerName} · {current.customerPhone}</p><p>{current.customerAddress}, {current.city}</p>{current.trackingNumber && <p className="mt-3">Tracking: {current.trackingNumber}</p>}{current.vendorShopOrders.map(s => <p key={s.shopOrderNumber} className="mt-3 text-sm">{s.shopOrderNumber} · {s.status}{s.trackingNumber ? ` · ${s.trackingNumber}` : ""}</p>)}</section><nav className="my-5 flex flex-wrap gap-4 font-bold text-brand-link"><Link href={`/invoice/${current.id}`}>View / print invoice</Link><Link href={`/track-order?order=${encodeURIComponent(current.orderNumber)}`}>Tracking timeline</Link>{current.hasDeliveredItems && <Link href="/my-stuff">Returns, warranty & after-sales</Link>}<Link href="/account/services">My services</Link></nav>{current.canCancel && <form id="cancel" onSubmit={e => void cancel(e)} className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-bold">Cancel this order</h2><label className="mt-4 block">Reason<input required name="reason" maxLength={500} className="mt-2 block w-full rounded-xl border p-3" /></label><button disabled={busy} className="mt-4 rounded-xl border border-red-300 px-5 py-3 font-bold text-red-700">Confirm cancellation</button></form>}</>}</main>;
}