"use client";
import { useCallback, useEffect, useState } from "react";
import { useSession } from "next-auth/react";
import { useSearchParams } from "next/navigation";
import Link from "next/link";
import Image from "next/image";
import { ProductCard, type ProductCardData } from "@/components/user/ProductCard";
import { accountDestinations } from "@/components/user/AccountNavigation";
import { useCustomerAuth } from "@/context/CustomerAuthContext";
import { useSavedProducts } from "@/lib/use-saved-products";
import { formatPKR } from "@/lib/format";
type Address = { id: string; label: string; recipientName: string; phone: string; address: string; city: string; postalCode: string | null; isDefault: boolean };
type Account = {
  profile: { name: string; email: string; phone: string; createdAt: string };
  orders: { id: string; orderNumber: string; orderStatus: string; paymentStatus: string; totalAmount: number; createdAt: string; canCancel: boolean; hasDeliveredItems: boolean; items: { id: string; name: string; quantity: number }[] }[];
  wants: { id: string; title: string; status: string; category: string; city: string; quantity: number; budgetMin: number | null; budgetMax: number | null; budgetFlexible: boolean; moderationReason: string | null; createdAt: string; expiresAt: string; interestCount: number; offerCount: number }[];
  savedProducts: (ProductCardData & { available: boolean })[];
  followedStores: { id: string; shopName: string; shopLogo: string | null; storeSlug: string | null; primaryCategory: string; city: string; status: string; _count: { followers: number } }[];
  addresses: Address[]; counts: Record<string,number>; pagination: { page: number; pageSize: number; orderPages: number; wantPages: number };
};
const fieldClass = "mt-1 block w-full min-w-0 rounded-xl border border-borderGray bg-white px-3 py-2.5 font-normal";
function Empty({ title, children }: { title: string; children: React.ReactNode }) { return <div className="rounded-2xl border border-dashed border-borderGray bg-white p-8 text-center"><h2 className="text-lg font-bold">{title}</h2><p className="mt-2 text-base text-darkText/65">{children}</p></div>; }
export default function AccountPage() {
  const { data: session, status, update } = useSession(); const { openAuthModal } = useCustomerAuth(); const saved = useSavedProducts(); const search = useSearchParams();
  const requestedTab = search?.get("tab") || "overview"; const tab = ["overview","orders","wants","saved","stores","addresses","profile"].includes(requestedTab) ? requestedTab : "overview"; const page = Math.max(1, Number.parseInt(search?.get("page") || "1",10) || 1);
  const customerId = session?.user?.role === "customer" ? session.user.id : "";
  const [data, setData] = useState<Account | null>(null); const [ownerId, setOwnerId] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [editing, setEditing] = useState<Address | "new" | null>(null);
  const load = useCallback(async (signal?: AbortSignal) => {
    if (!customerId) return; setLoading(true); setError("");
    try { const r = await fetch(`/api/customer/account?page=${page}`, { signal, cache: "no-store" }); const d = await r.json(); if (!r.ok) throw new Error(d.error || "Could not load account."); if (!signal?.aborted) { setData(d); setOwnerId(customerId); } }
    catch(e) { if (!signal?.aborted) setError(e instanceof Error ? e.message : "Could not load account."); } finally { if (!signal?.aborted) setLoading(false); }
  }, [customerId,page]);
  useEffect(() => { setData(null); setEditing(null); const controller = new AbortController(); void load(controller.signal); const refresh = () => { void load(controller.signal); }; window.addEventListener("customer-saved-products-changed",refresh); return () => { controller.abort(); window.removeEventListener("customer-saved-products-changed",refresh); }; }, [load]);
  async function mutate(url: string, method: string, body?: unknown) {
    setBusy(true); setError(""); setMessage("");
    try { const r = await fetch(url, { method, headers: { "Content-Type": "application/json" }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error || "Could not save changes."); setMessage("Changes saved."); setEditing(null); await load(); return true; }
    catch(e) { setError(e instanceof Error ? e.message : "Could not save changes."); return false; } finally { setBusy(false); }
  }
  async function saveAddress(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault(); const f = new FormData(e.currentTarget); const current = editing && editing !== "new" ? editing : null;
    await mutate(`/api/customer/addresses${current ? `/${current.id}` : ""}`, current ? "PATCH" : "POST", { label: f.get("label"), recipientName: f.get("recipientName"), phone: f.get("phone"), address: f.get("address"), city: f.get("city"), postalCode: f.get("postalCode") || null, isDefault: f.get("isDefault") === "on" });
  }
  async function saveProfile(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const name = String(f.get("name")); const phone = String(f.get("phone")); if (await mutate("/api/customer/profile","PATCH",{ name,phone })) { try { const response = await fetch("/api/customer/profile", { cache: "no-store" }); if (!response.ok) throw new Error("Session refresh failed"); const result = await response.json(); await update({ name: result.name, phone: result.phone }); } catch { setMessage("Profile saved. Refresh to update your session display."); } } }
  if (status === "loading") return <div className="p-10 text-center" role="status">Loading your account…</div>;
  if (!customerId) return <main className="mx-auto max-w-xl px-4 py-12 text-center"><h1 className="text-3xl font-bold">My JORO</h1><p className="my-4">Sign in to view your private account, orders, and saved items.</p><button onClick={() => openAuthModal("login")} className="rounded-xl bg-brand-primary px-6 py-3 font-bold">Sign in</button></main>;
  const current = ownerId === customerId ? data : null;
  if (!current) return <main className="mx-auto max-w-3xl p-8"><h1 className="text-3xl font-bold">My JORO</h1><p className="my-4" role={error ? "alert" : "status"}>{error || "Loading your account…"}</p>{error && <button onClick={() => void load()} className="rounded-xl bg-brand-primary p-3">Try again</button>}</main>;
  const title = accountDestinations.find(([id]) => id === tab)?.[1] || "Overview";
  const address = editing && editing !== "new" ? editing : null;
  const pages = tab === "orders" ? current.pagination.orderPages : tab === "wants" ? current.pagination.wantPages : 0;
  return <main className="mx-auto max-w-7xl px-4 py-8 sm:px-6"><p className="text-sm font-bold text-brand-link">My JORO</p><h1 className="mt-1 text-3xl font-bold">{title === "Overview" ? `Welcome, ${current.profile.name}` : title}</h1>{error && <p className="my-4 rounded-xl bg-red-50 p-4 text-red-800" role="alert">{error}</p>}{message && <p className="my-4" role="status">{message}</p>}{loading && <p className="my-3 text-sm" role="status">Refreshing…</p>}<section className="mt-6">
    {tab === "overview" && <><p className="mb-5 text-darkText/65">Your orders, shopping activity, and after-sales support in one place.</p><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["orders","Orders","/account?tab=orders"],["wants","My Wants","/account?tab=wants"],["offers","Received Offers","/account/offers"],["saved","Saved Products","/account?tab=saved"],["following","Following Stores","/account?tab=stores"],["unread","Unread Notifications","/account/notifications"],["returns","Return Requests","/my-stuff?tab=returns"],["services","Booked Services","/account/services"]].map(([key,label,href]) => <Link key={key} href={href} className="rounded-2xl border border-borderGray bg-white p-5 shadow-card"><p className="text-base text-darkText/65">{label}</p><p className="mt-2 text-3xl font-bold">{current.counts[key]}</p></Link>)}</div><Link href="/my-stuff" className="mt-6 inline-block rounded-xl bg-brand-soft px-5 py-3 font-bold text-brand-link">My Stuff: purchases, warranties & support</Link></>}
    {tab === "orders" && (current.orders.length ? <div className="space-y-4">{current.orders.map(o => <article key={o.id} className="rounded-2xl border bg-white p-5 shadow-card"><div className="flex flex-wrap justify-between gap-3"><h2 className="text-lg font-bold">{o.orderNumber}</h2><p className="font-bold">{formatPKR(o.totalAmount)}</p></div><p className="my-2 text-sm text-darkText/65">{new Date(o.createdAt).toLocaleString("en-PK")} · {o.orderStatus.replaceAll("_"," ")} · Payment {o.paymentStatus.replaceAll("_"," ")}</p><ul className="my-4 space-y-1">{o.items.map(i => <li key={i.id}>{i.name} × {i.quantity}</li>)}</ul><div className="flex flex-wrap gap-3 text-sm font-bold text-brand-link"><Link href={`/account/orders/${o.id}`}>Order details</Link><Link href={`/track-order?order=${encodeURIComponent(o.orderNumber)}`}>Track</Link><Link href={`/invoice/${o.id}`}>Invoice</Link>{o.canCancel && <Link href={`/account/orders/${o.id}#cancel`}>Cancel order</Link>}{o.hasDeliveredItems && <Link href="/my-stuff">Returns / After-sales</Link>}</div></article>)}</div> : <Empty title="No orders yet">Your orders will appear after checkout.</Empty>)}
    {tab === "wants" && <><Link href="/wants/new" className="mb-5 inline-block rounded-xl bg-brand-primary px-4 py-3 font-bold">Post a Want</Link>{current.wants.length ? <div className="grid gap-4 md:grid-cols-2">{current.wants.map(w => <article key={w.id} className="rounded-2xl border bg-white p-5"><Link href={`/wants/${w.id}`} className="text-lg font-bold">{w.title}</Link><p className="my-2">{w.category} · {w.city} · Qty {w.quantity}</p><p className="text-sm">{w.budgetFlexible ? "Budget flexible" : `PKR ${(w.budgetMin || 0).toLocaleString("en-PK")} – ${(w.budgetMax || 0).toLocaleString("en-PK")}`}</p><p className="mt-1 text-sm">{w.status.replaceAll("_"," ")} · {w.interestCount} interested · {w.offerCount} offers</p>{w.moderationReason && <p className="mt-2 text-sm font-semibold text-red-700">Note: {w.moderationReason}</p>}<p className="mt-2 text-sm text-darkText/65">Created {new Date(w.createdAt).toLocaleDateString("en-PK")} · Expires {new Date(w.expiresAt).toLocaleDateString("en-PK")}</p></article>)}</div> : <Empty title="No Wants yet">Your own posted Wants will appear here.</Empty>}</>}
    {tab === "saved" && <><p className="mb-4 text-sm text-darkText/65">Unavailable listings stay here until you unsave them. Deleted catalog products are removed automatically.</p>{current.savedProducts.length ? <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{current.savedProducts.map(p => <div key={p._id}>{p.available ? <ProductCard product={p} /> : <article className="rounded-2xl border bg-white p-5"><h2 className="font-bold">{p.name}</h2><p className="my-3">Currently unavailable.</p><button disabled={saved.saving} onClick={() => void saved.toggle(p._id)} className="font-bold text-brand-link underline">Unsave product</button></article>}</div>)}</div> : <Empty title="Nothing saved yet">Use the heart on a product to save it to your account.</Empty>}</>}
    {tab === "stores" && (current.followedStores.length ? <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{current.followedStores.map(s => <article key={s.id} className="rounded-2xl border bg-white p-5"><div className="flex items-center gap-3">{s.shopLogo && <Image src={s.shopLogo} alt="" width={48} height={48} unoptimized className="h-12 w-12 rounded-xl object-cover" />}<h2 className="text-lg font-bold">{s.shopName}</h2></div><p className="my-3">{s.primaryCategory} · {s.city}</p><p className="text-sm">{s._count.followers} followers</p><div className="mt-4 flex flex-wrap gap-4 text-sm font-bold text-brand-link">{s.status === "approved" && s.storeSlug ? <Link href={`/stores/${encodeURIComponent(s.storeSlug)}`}>View Store</Link> : <span className="text-darkText/60">Store currently unavailable</span>}<button disabled={busy} onClick={() => void mutate(`/api/stores/${s.id}/follow`,"DELETE")}>Unfollow</button></div></article>)}</div> : <Empty title="No followed stores">Follow a store to keep it here.</Empty>)}
    {tab === "addresses" && <><button onClick={() => setEditing("new")} className="mb-5 rounded-xl bg-brand-primary px-4 py-3 font-bold">Add address</button>{editing && <form key={address?.id || "new"} onSubmit={e => void saveAddress(e)} className="mb-6 grid gap-4 rounded-2xl border bg-white p-5 sm:grid-cols-2"><h2 className="text-xl font-bold sm:col-span-2">{address ? "Edit" : "Add"} delivery address</h2>{([['label','Label',60],['recipientName','Recipient name',200],['phone','Phone',40],['postalCode','Postal code (optional)',30],['city','City',120]] as const).map(([name,label,max]) => <label key={name}>{label}<input className={fieldClass} name={name} defaultValue={address?.[name] || ""} required={name !== "postalCode"} maxLength={max} /></label>)}<label>Street address<textarea className={fieldClass} name="address" rows={3} defaultValue={address?.address || ""} minLength={5} maxLength={2000} required /></label><label className="flex items-center gap-2"><input name="isDefault" type="checkbox" defaultChecked={address?.isDefault} />Default delivery address</label><p className="text-sm text-darkText/65">Your first address becomes the default. At least one remains default while addresses exist.</p><button disabled={busy} className="rounded-xl bg-brand-primary p-3 font-bold">Save address</button><button type="button" onClick={() => setEditing(null)}>Cancel edit</button></form>}{current.addresses.length ? <div className="grid gap-4 md:grid-cols-2">{current.addresses.map(a => <article key={a.id} className="rounded-2xl border bg-white p-5"><h2 className="text-lg font-bold">{a.label}{a.isDefault ? " · Default" : ""}</h2><p className="my-2">{a.recipientName} · {a.phone}</p><p>{a.address}, {a.city} {a.postalCode}</p><div className="mt-4 flex flex-wrap gap-4 text-sm font-bold text-brand-link"><button disabled={busy} onClick={() => setEditing(a)}>Edit</button>{!a.isDefault && <button disabled={busy} onClick={() => void mutate(`/api/customer/addresses/${a.id}`,"PATCH",{ isDefault: true })}>Make default</button>}<button disabled={busy} onClick={() => void mutate(`/api/customer/addresses/${a.id}`,"DELETE")}>Delete address</button></div></article>)}</div> : <Empty title="No addresses saved">Add a delivery address for future checkout.</Empty>}</>}
    {tab === "profile" && <form onSubmit={e => void saveProfile(e)} className="max-w-xl space-y-5 rounded-2xl border bg-white p-6"><label className="block">Name<input className={fieldClass} name="name" defaultValue={current.profile.name} maxLength={200} required /></label><label className="block">Phone<input className={fieldClass} name="phone" defaultValue={current.profile.phone} maxLength={40} /></label><div><p className="text-sm text-darkText/65">Email</p><p className="break-all">{current.profile.email}</p></div><p className="text-sm text-darkText/65">Member since {new Date(current.profile.createdAt).toLocaleDateString("en-PK")}</p><button disabled={busy} className="rounded-xl bg-brand-primary px-5 py-3 font-bold">Save profile</button></form>}
  </section>{pages > 1 && <nav aria-label="Account list pages" className="mt-6 flex flex-wrap items-center gap-4">{page > 1 && <Link href={`/account?tab=${tab}&page=${page-1}`} className="rounded-xl border p-3">Previous</Link>}<span>Page {page} of {pages}</span>{page < pages && <Link href={`/account?tab=${tab}&page=${page+1}`} className="rounded-xl border p-3">Next</Link>}</nav>}</main>;
}